"""empty message

Revision ID: 0393fc2d1530
Revises: cbf965668806
Create Date: 2023-12-13 16:11:44.836332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0393fc2d1530'
down_revision = 'cbf965668806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tertiaryapplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Phonenumber', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('levelofstudy', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tertiaryapplication', schema=None) as batch_op:
        batch_op.drop_column('levelofstudy')
        batch_op.drop_column('Phonenumber')

    # ### end Alembic commands ###
