"""assistantchief

Revision ID: 212d6fcfa063
Revises: 752442c86d74
Create Date: 2023-12-27 19:05:14.973065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212d6fcfa063'
down_revision = '752442c86d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tertiaryapplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Assistantchiefno', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tertiaryapplication', schema=None) as batch_op:
        batch_op.drop_column('Assistantchiefno')

    # ### end Alembic commands ###
