"""Add image_url column

Revision ID: 6524e43c4f16
Revises: c763f7ab6648
Create Date: 2024-12-16 10:57:26.415541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6524e43c4f16'
down_revision = 'c763f7ab6648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tertiaryapplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageurl', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tertiaryapplication', schema=None) as batch_op:
        batch_op.drop_column('imageurl')

    # ### end Alembic commands ###
