"""university

Revision ID: b118bf1f11d8
Revises: 212d6fcfa063
Create Date: 2023-12-27 19:41:01.238232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b118bf1f11d8'
down_revision = '212d6fcfa063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tertiaryapplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('University', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tertiaryapplication', schema=None) as batch_op:
        batch_op.drop_column('University')

    # ### end Alembic commands ###
