"""imageurl

Revision ID: e0cdc26a8058
Revises: 6524e43c4f16
Create Date: 2024-12-16 11:55:30.944283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cdc26a8058'
down_revision = '6524e43c4f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tertiaryapplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Imageurl', sa.String(), nullable=True))
        batch_op.drop_column('imageurl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tertiaryapplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageurl', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('Imageurl')

    # ### end Alembic commands ###
